### ISSUE TITLE
[TNG] Class 'MetaModels\DcGeneral\Events\MetaModels\Select\BackendSubscriber' not found

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_tags#22]
Ich habe mir gerade einen frischen TNG über composer installiert, dort erhalte ich jetzt im Backend folgende Meldung:
```

Fatal error: Class 'MetaModels\DcGeneral\Events\MetaModels\Select\BackendSubscriber' not found in /Applications/MAMP/htdocs/metamodels/contao/composer/vendor/contao-community-alliance/event-dispatcher/src/ContaoCommunityAlliance/Contao/EventDispatcher/EventDispatcherInitializer.php on line 183
```
Das Problem liegt hier: https://github.com/MetaModels/attribute_tags/blob/33ef95e4887e64394ad4cb3347b65b529d890210/contao/config/config.php#L18 und entsteht meiner Meinung nach daraus, das in der composer.json vom Attribute-Tags das Require auf das Select-Attribute fehlt: https://github.com/MetaModels/attribute_tags/blob/tng/composer.json#L46

**Comment by discordier** [comment]
Da das tags attribute nun seinen eigenen subscriber hat, kann das require wieder raus, oder?

**Comment by xantippe** [comment]
@cboelter Ticket noch aktuell?

**Comment by zonky2** [comment]
gefixt
