### ISSUE TITLE
"Ergebnisse zählen" hat keine Funktion mehr...

### ISSUE THREAD

**Issue by kein-nickname** [MetaModels/attribute_tags#26]
Seit einem der letzten Updates hat der Filter "Tags" wie auch schon "Select" keine Funktion mehr, wenn man bei den Frontendfilter die  Einstellung "Ergebnisse zählen" aktviert... es werden keine Werte mehr angezeigt!!!

**Comment by discordier** [comment]
Kannst du mal probieren ob das Problem mit https://github.com/MetaModels/attribute_tags/commit/beb10b9a16a1089bd7b8607898d399c299e5c82d weg ist?

**Comment by kein-nickname** [comment]
Also bei mir hat sich diesbezüglich keine Änderung ergeben.
Kann es sein, dass das Ganze ein Fehler im Template ist und die Daten an eine andere Variable übermittelt werden.
Mir kommt es vor als ob die $option['key'] keinen Wert mehr ausliefert...

**Comment by kein-nickname** [comment]
@discordier Also bei mir hat sich diesbezüglich keine Änderung ergeben.
Kann es sein, dass das Ganze ein Fehler im Template ist und die Daten an eine andere Variable übermittelt werden.Mir kommt es vor als ob die $this->count[$option['key']] keinen Wert mehr ausliefert...

**Comment by discordier** [comment]
Was steht allgemein in `$this->count` drin?

**Comment by kein-nickname** [comment]
Keine Ahnung ist das Standard-Template :-o
Ging auch bis vor einigen Wochen und seit dem kommen nur noch ()

**Comment by discordier** [comment]
Dann mach doch mal bitte einen `var_dump($this->count);` und poste uns das Ergebnis.

**Comment by kein-nickname** [comment]
Bei Select-Filter wird folgendes angezeigt
```
array(0) { } array(0) { } array(0) { }
array(0) { } array(0) { } 
```

Bei Tags-Filtern
```
array(1) { [""]=> string(1) "4" }
array(1) { [""]=> string(1) "4" }
array(1) { [""]=> string(1) "4" } 
```

**Comment by discordier** [comment]
Also wurde beim select gar nicht gezaehlt und bei den tags sind die ids nicht vorhanden.
Wie genau sieht deine Konfiguration der Filter aus?

**Comment by Zeromax** [comment]
@discordier kann ich verifizieren das Problem. Muss mich dahinterklemmen, evtl. nur ein Logik Problem, der Code ist ja noch da ;)
Mache einen PR, wenn ich es gefixed habe. Sollte nächste Woche der Fall sein.
Mein Letzter Stand, als es noch ging war vom November 2014 ...

**Comment by discordier** [comment]
Nun sollten wieder Anzahlen von Treffern kommen.

**Comment by Zeromax** [comment]
@discordier nun es werden wieder Zahlen ausgegeben, das ist richtig.
Allerdings haben die Zahlen keinen Alias Bezug.

Und sie sind auch nur gültig wenn `$used==false` ist.
Das versuchte ich hier https://github.com/MetaModels/attribute_tags/pull/37#issuecomment-74475618 zu erklären.
Die komplette used SQL Logik fehlt in der `MetaModelTags` Klasse.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?

**Comment by Aybee** [comment]
Das liegt daran, dass im FE Template ohne weitere Programmierung keine Zuordnung von count auf die options oder umgekehrt gemacht werden kann.
```php
[raw] => Array
    (
        [options] => Array
            (
                [aepfel] => Äpfel
                [birnen] => Birnen
            )

        [count] => Array
            (
                [2] => 23
                [7] => 15
            )
[options] => Array
    (
        [0] => Array
            (
                [key] =>
                [value] => Nicht filtern
            )
        [1] => Array
            (
                [key] => aepfel
                [value] => Äpfel
            )
        [2] => Array
            (
                [key] => birnen
                [value] => Birnen
            )
    )
[count] => Array
    (
        [2] => 23
        [7] => 15
    )
```
Zumindestens ist das so, wenn man Aliase für die Options benutzt. Die options bräuchten eine weitere Variable **id**.
```php
[options] => Array
    (
        [0] => Array
            (
                [id] => 
                [key] =>
                [value] => Nicht filtern
            )
        [1] => Array
            (
                [id] => 2
                [key] => aepfel
                [value] => Äpfel
            )
        [2] => Array
            (
                [id] => 7
                [key] => birnen
                [value] => Birnen
            )
    )
[count] => Array
    (
        [2] => 23
        [7] => 15
    )
```
Danach könnte man die Templates ändern
```php
// von
(($this->showCount) ? ' <span class="count">('. $this->count[$option['key']] .')</span>' : '')
// nach
(($this->showCount && $option['id']) ? ' <span class="count">('. $this->count[$option['id']] .')</span>' : '')
```

**Comment by discordier** [comment]
Please test again, it is now working for me.

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@kein-nickname could you please have a final look at this and tell if your issue has been resolved?
