### ISSUE TITLE
Es werden nicht alle ausgewählten Tags ausgegeben

### ISSUE THREAD

**Issue by tniebergall** [MetaModels/attribute_tags#28]
Ich habe aktuell das problem unter Contao 3.3.7 und der aktuelle tng, dass die Ausgabe der Tags im Frontend nicht vollständig erfolgt.

In allen items meines MM haben ich je item mehrere Tags ausgewählt und diese werden auch im Backend (DB) korrekt gespeichert.
In der Frontendausgabe über ein Listen Element werden bei manchen items die Tags ausgegeben bei anderen wird nur NULL übergeben.

Gerne kann ich einen Zugang für das Debugging bereitstellen.

Danke

**Comment by fabian-ibr** [comment]
Ich habe das Problem mit der aktuellen tng auch. In der Listenansicht gibt er die Tags immer nur einmal aus. (Beim ersten Eintrag.)

**Comment by tniebergall** [comment]
Bei mir funktioniert es mit dieser Anpassung.

Danke @stefanheimes

**Comment by fabian-ibr** [comment]
Bei mir auch. Besten Dank.
