### ISSUE TITLE
[TNG] Kein submitOnChange in den DCA-Settings verfügbar - WIP

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_tags#31]
In den DCA-Settings des Attributes fehlt die Möglichkeit submitOnChange zu aktivieren. Somit ist eine Nutzung als Condition nicht möglich.

**Comment by cboelter** [comment]
@discordier Kannst du mir hier feedback geben, ob sich das kurzfristig umsetzen lässt. Bräuchte das Feature oder eine Info :) ...

**Comment by discordier** [comment]
Sollte analog zu den selects implementierbar sein (sofern die widgets es verstehen).

**Comment by cboelter** [comment]
Ok, werde ich mir in den kommenden Tagen einmal ansehen.

**Comment by cboelter** [comment]
Ich arbeite aktuell an dem Feature.
