### ISSUE TITLE
PHP Recoverable error: Argument 1 passed to Contao\Ajax::executePostActionsHook() 

### ISSUE THREAD

**Issue by markknochen1** [MetaModels/attribute_tags#34]
Beim Zuweisen von Werten zum attr_tags innerhalb eines MM-Eintrages bekam ich eben den Fehler:

PHP Recoverable error: Argument 1 passed to Contao\Ajax::executePostActionsHook() must be an instance of DataContainer, instance of ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat given, called in system/modules/core/classes/Ajax.php on line 211 and defined in system/modules/core/classes/Ajax.php on line 422

Die Zuweisungen werden auch in der Tabelle tl_metamodel_tag_relation nicht gespeichert.

**Comment by discordier** [comment]
Should be fixed by contao-community-alliance/dc-general@40c85ffe86f90843935ba43acede4e74fe5cfdf2
