### ISSUE TITLE
Endlosschleife bei auf sich selbst referenziertem MM

### ISSUE THREAD

**Issue by design23** [MetaModels/attribute_tags#35]
Bezugnehmend auf folgenden Thread:
https://community.contao.org/de/showthread.php?55394-MM-auf-sich-selbst-referenzieren

Hier mein Vorgehen (in Bildern, wie gewünscht):

Grundeinstellungen des MM:
![bildschirmfoto 2015-02-04 um 10 45 10](https://cloud.githubusercontent.com/assets/6112308/6038232/98278d4c-ac5b-11e4-9aea-905a2d432fcc.png)

Attribute:
![bildschirmfoto 2015-02-04 um 10 45 31](https://cloud.githubusercontent.com/assets/6112308/6038242/aba052aa-ac5b-11e4-8989-550d657a02ad.png)

Speziell das Attribut Mehrfachauswahl:
![bildschirmfoto 2015-02-04 um 10 45 48](https://cloud.githubusercontent.com/assets/6112308/6038254/ba52ee3e-ac5b-11e4-956c-057a24158878.png)

Einstellungen der Eingabemaske:
![bildschirmfoto 2015-02-04 um 10 46 44](https://cloud.githubusercontent.com/assets/6112308/6038268/cab0b752-ac5b-11e4-9b8e-eb1d8e841e63.png)

Die MM-Einträge:
![bildschirmfoto 2015-02-04 um 10 47 01](https://cloud.githubusercontent.com/assets/6112308/6038273/d8e04040-ac5b-11e4-8f2e-6dfdd9717fb7.png)

Beim ersten lässt sich das ganze noch speichern:
![bildschirmfoto 2015-02-04 um 10 47 11](https://cloud.githubusercontent.com/assets/6112308/6038280/e54bbe9a-ac5b-11e4-92d6-2aa5c997a789.png)

Beim zweiten ist das Schluss -> Browser lädt sich zu Tode... und das Ende ist eine Fehlermeldung, die besagt, dass das memory limit erreicht wurde.
![bildschirmfoto 2015-02-04 um 10 47 22](https://cloud.githubusercontent.com/assets/6112308/6038290/f70acb6c-ac5b-11e4-895d-90c7c30fe285.png)

**Comment by discordier** [comment]
@stefanheimes We need to add a tracking of recursion here.

**Comment by design23** [comment]
Konntet ihr das Verhalten reproduzieren?

**Comment by davidmaack** [comment]
Wie wäre es mit einer Checkbox, mit der man das Standard-Attribut erwingen kann? Damit würde in der AttributeTypeFactory nicht dass MetaModelTags geladen, sonder die "einfache" Tag-Klasse. 

Ja, dann muss man bei der Anzeige im Template die Verlinken Items selber raussuchen, aber man könnte im Backend die Produkte pflegen und zur Ausgabe bringen. Das wäre relative schnell umgesetz und wäre für viele eine Lösung, bis das Tracking der Rekursion implementiert hat.....

**Comment by markus151173** [comment]
Als Zwischenlösung gäbe es die Möglichkeit in der AttributeTypeFactory.php in Zeile 48 die if Abfrage raus zu nehmen. Ist aber dann nicht mehr Ubdatesicher. 
\system\modules\metamodelsattribute_tags\classes\src\MetaModels\Attribute\Tags

Das mit der Checkbox wäre die besser Lösung.

**Comment by davidmaack** [comment]
Sollte 1349e20222ca8e0e06a9d2ab2362508b91c4223d das Problem nicht behoben haben?

**Comment by discordier** [comment]
Gab noch ein Problem, dbe75f620c2d82ce6ef711eae28b4ee104d672f7 sollte es komplett beheben.

**Comment by design23** [comment]
Ich komme leider erst in ein paar Tagen dazu, das zu testen. Werde dann entsprechend nochmal Feedback geben. Danke schonmal vorab!

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@design23 could you please have a final look at this and tell if your issue has been resolved?

**Comment by gruenerPetz** [comment]
Ist das Problem endgültig gelöst? Ich habe ein ähnliches Problem.
Ich habe auch eine Beziehung products <-> related products und beim Editieren der Produkte gibt es Probleme.
Der Debug Modus zeigt, dass ich extrem viele Database queries habe, wenn ich das Tag Plugin aktiviere.

Installiert ist Version 2.0.2

**Comment by zonky2** [comment]
@gruenerPetz 

* da auf das Testing niemand reagiert hat, gilt es als gelöst: also JA
* welche Probleme hast Du?
* was sind extrem viele Queries?
* wie kann das Verhalten nachvollzogen/nachgebaut werden?

**Comment by gruenerPetz** [comment]
Ich habe wie design23 mm_products und mit dem tags attribute related products verbunden. Wenn ich jetzt ein Produkt öffne, zeigt es im im Debug Modus ohne Tags Attribut ca. 160 Queries an und mit über 600 Queries an. Mit zunehmender Produkte werden auch die Queries mehr, bis es eben beim speichern zum Absturz kommt.

Ich habe das Gefühl es werden alle Daten auch von den related products geladen.
Es sind mehrere Tags Attribute im Einsatz, aber die Selbstreferenzierung macht die Probleme.

**Comment by design23** [comment]
Oh Himmel... ich hatte damals ja gar nicht mehr geantwortet... sorry!
Ich konnte das damals gar nicht mehr testen, da aus Zeitgründen eine andere Lösung umgesetzt werden musste. Daher konnte ich das leider nicht testen.
Abe die Fehlerbeschreibung von gruenerPetz klingt, als wäre es genau das gleiche Problem wie damals.

**Comment by zonky2** [comment]
dann mache ich mal ein reopen...

aktuell wird das vom MM-Team wohl keiner "nebenbei" debuggen können - ggf. kannst Du Dich mal "reinwurschteln"

**Comment by MiniModel** [comment]
This issue has been labeled with testing but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@design23 could you please have a final look at this and tell if your issue has been resolved?
