### ISSUE TITLE
Property faecher (tags) did not accept the value

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/attribute_tags#39]
hallo,

mit dem aktuellen nightbuild von gestern bekomme ich folgende fehlermeldung,
wenn ich das attribut "mehrfachauswahl [tags]" verwende und dann einen eintrag
im metamodel vornehmen möchte:

Property faecher (tags) did not accept the value (The values differ. Array value mismatch for key 0. Encountered type integer expected string (Found 1, expected '1')).

Property faecher (tags) did not accept the value (The values differ. Array value mismatch for key 0. Encountered type integer expected 

hat jemand eine idee?

lg.

alex

https://community.contao.org/de/showthread.php?56322-tags-fehlermeldung&p=363687#post363687

**Comment by discordier** [comment]
Sollte seit eff535e1d6ce2fd12f6593efce467a30911fdbcf behoben sein.

**Comment by haendersonfox** [comment]
mit dem aktuellen nightly ist der fehler behoben... sehr sch�n, vielen dank.


Am 24.03.2015 um 18:35 schrieb Christian Schiffler:

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@haendersonfox could you please have a final look at this and tell if your issue has been resolved?

**Comment by Kreativsoehne** [comment]
Property attribut-name (tags) did not accept the value (The values differ. Array value mismatch for key 0. Found 'abc' expected 'xyz').

Leider scheint der Fehler noch nicht behoben zu sein... (MetaModel Stand vom 02.04.2015)

**Comment by discordier** [comment]
Hast du mir bitte Details zu deiner Konfiguration?
Insbesondere wonach deine Tag Werte sortiert werden.

**Comment by Kreativsoehne** [comment]
Hallo :)
Sorry für die späte Antwort... habe die Nachricht übersehen.

In der Eingabemaske ist es ein Attributtyp: tags - welches auf eine anderes metamodel zugreift.
Der Checkbox-Wizard ist auf "Display as tag list" - wobei eine Änderung keine Auswirkung auf das Verhalten zeigt.
Es gibt keine "Visibility conditions für dieses Attribut"
Im entsprechenden Metamodel für die tag-Werte gibt es eine Backend-Sortierung nach Name und Stimme.
Gibt es weitere bzw. andere Angaben die dir zur Behebung weiterhelfen könnten?
Gern auch Zugriff auf das Projekt...

**Comment by Znrl** [comment]
Hab ich auch:
Property author (tags) did not accept the value (The values differ. Array value mismatch for key 0. Found 'one_alias' expected 'two_alias').

Ändern des Alias scheint erstmal nicht zu helfen. Es fuktioniert auch nur diese kombination nicht, wenn ich ein drittes Tag hinzufüge oder eins austausche geht es.

**Comment by Znrl** [comment]
Ok ich hab das mit dem sorting erst überlesen... das stand auf auf Sortieren nach "sorting" allerdings ist sorting überall 0. Ich hab das mal auf nach ID sortieren umgestellt und es scheint ertmal zu gehen.

**Comment by discordier** [comment]
Wieso sind die in der Datenbank alle auf 0? Hast du kein manuelles sortieren in der Fremdtabelle definiert?

**Comment by Znrl** [comment]
Ich habs so mit den Datenbanken ... (aber letzts mal hatte es nichts mit MM zu tun)
Ich hatte 3 sortings drin, nachdem ich jetzt das manuelle auf standard gesetzt habe werden in der Datenbank fürs sorting auch Werte gesetzt.
Ich hate das vorher ignoriert, weil es das manuelle sorting nie gespeichert hat (läuft aber auch schon länger vtl. giengs am Anfang auch wirklich noch nicht). Man müsste das vtl. nochmal frisch aufsetzen... aber so siehts aus als würde manuelles sorting nur dann funktionieren (bzw Werte in die DB schreiben), wenns auf standard steht.
Ist das so gewollt, weil nicht standard = temporär?

**Comment by Kreativsoehne** [comment]
Bei mir verhält es sich etwas anders.
Wenn ich das Attribut anlege, dann kann ich einmalig Daten zuordnen. Wenn diese einmal gespeichert sind und ich etwas an den zugeordneten Daten ändern möchte kommt der Fehler. Weder hinzufügen noch entfernen von Werten geht dann...

**Comment by Kreativsoehne** [comment]
Wir brauchen hier dringend eine Lösung...
Testsystem vorhanden, gern auch gemeinsame Session dazu...

**Comment by discordier** [comment]
Was hast du bei deiner Attributskonfiguration als sortierspalte eingetragen?

**Comment by Kreativsoehne** [comment]
Die Spalte Sorting...

**Comment by discordier** [comment]
Welche lauter nullen beinhaltet und somit die Eintraege von MySQL "random" geliefert werden. Da ist es dann logisch dass sich die Reihenfolge immer hin und her aendert.

**Comment by Kreativsoehne** [comment]
Okay, nicht dass wir aneinander vorbei reden:
Es handelt sich um eine Verwaltung für klassische Konzerte. In jedem Konzert singen Solisten. Diese sind bereits als Metamodel vorhanden und sollen nun über eine Mehrfachauswahl einem Konzert zugewiesen werden. Wie bereits erwähnt, funktioniert die Erstauswahl dieser Personen ohne Probleme. Aber bei einer nachträglichen Änderung der Solisten-Zuordnung gibt es zwei verschiedene Verhaltensweisen:

### Hinzufügen eines oder mehrerer Solisten
Hierbei erscheint die Fehlermeldung:
    Property concert_soloists (tags) did not accept the value (The values differ. Array value mismatch for key 0. Found 'julia-sophie-wagner' expected 'joanne-lunn').

Nachdem dem Attribut keine Sortierung mehr zugewiesen wurde, kann man die Werte nun zuordnen und auch entfernen. Danke für den Hinweis. 
Aber: Nach meinem Verständnis sollte doch eine Sortierung an der Stelle egal sein, da es lediglich um die Verknüpfung eines MM-Eintrags mit mehreren anderen geht. Das Verhalten ist an dieser Stelle einfach unerwartet und man kommt nicht auf die Idee, dass es an einer Sortierungs-Einstellung liegen kann. Es ist damit zwar keine kritische Sache mehr, vielleicht findet sich ja in Zukunft eine etwas leichtgänigere Lösung.

### Entfernen aller Solisten
Will man alle Einträge auf einmal entfernen (zugegeben, das ist ein seltener Fall), passiert gar nichts. Der Eintrag bleibt nach dem Speichern wie er war. Es gibt keine Fehlermeldung und auch keinen Log-Eintrag. Auch die Umstellung auf keine Sortierung hat keinen Effekt.
Ich glaube nicht, dass dieser Fall in unserem Projekt tatsächlich so auftauchen wird, aber der Kunde ist sehr pingelig und wird garantiert darüber stolpern. Außerdem kann dieses Verhalten für andere MM-Nutzer zu einem echten Problem werden.

Wie gesagt: Wenn ein Zugang zum System gewünscht ist, um das Problem nachvollziehen zu können, dann ist das möglich.

Danke erst einmal für die Hilfe :)

**Comment by MacKP** [comment]
Hallo Kreativsoehne,
das mit dem Sorting muss einfach sein. Ist so muss man nur wissen und sich merken (wird dann irgendwann auch in irgendeiner Doku vermerkt).
Ich habe aber gerade mal versucht dein anderes Problem nachzustellen. Ich habe Tags wo ich dann mehrere (alle) Zuordnungen entferne und speicher. Die sind dann auch weg. Ich hab also nicht das von dir beschriebene Problem. Kannst du mal bitte auf die aktuelle Version gehen und das noch mal testen? MM Cache leeren nicht vergessen.

**Comment by Kreativsoehne** [comment]
Danke für deine Info... dann merken wir uns das mal ;)
Aber wir sind auf der aktuellsten Version (die unter https://now.metamodel.me/de/ressourcen/nightly-builds als zip angeboten wird) - auch extra nochmal gedifft um sicher zu gehen...
MetaModel Cache wird auch regelmäßig geleert.
Und nun?

**Comment by MacKP** [comment]
Hmm einziger Unterschied könnte sein, das ich translated nutzte an der Stelle.
Eventuell hängt ja was bei dir und nach einer komplett Neuzuweisung gehts dann richtig?
Ich hab da eigentlich keine wirkliche Idee wo das nun hängen könnte bei dir.. ich kanns wie gesagt leider (oder zum Glück) nicht nachstellen.

**Comment by Kreativsoehne** [comment]
Ich habe gerade alle Zuweisungen entfernt... leider bringt dies keine Abhilfe...
Ein vollständiges leeren des Attributes über die Eingabemaske ist nicht möglich :(

**Comment by Znrl** [comment]
Das ist aber nicht "required"?

Zu dem Sorting:
Momentan ist Manuelles Sortieren als zusätzliche Option ziemlich unbrauchbar.
(Es können mehrere Sortieroptionen gleichzeitig als "Is default" gesetzt werden !?)
Wenn manuelles Sortieren nicht Standard ist werden die "sorting" Werte nicht gesetzt oder geupdated.
Bei Attributen fürs Sortieren spielt das wohl (meist?) keine Rolle, da ein Sortieren nach Text bspw. immer gleich ist.
Würden die "sorting" Werte gesetzt könnte man das im Backend sinnvoll einsetzen und würde auch auf einige der Probleme oben nicht stoßen.
Allerdings ein manuelles sorting als default führt bei mir dazu, dass andere Sortiermöglichkeiten im Backend nicht funktionieren, die Reihenfolge ändert sich nicht.
Bei einer anderen Sortierung als default kann man zwischen den eingestellten Sortier optionen wechseln. Nur eben, dass die manuelle Sortierung nicht gespeichert wird.

**Comment by MacKP** [comment]
Hä? Das wäre jetzt wenn, dann in einem neuen Ticket sinnig @Znrl 
Aber mal zur Erleuchtung:
Das Sorting was du beim Attribut (tags) hier einstellst, das ist unabhängig von dem sorting was du bei dem MM was du als Grundlage einstellst (da kann ja mehrere Einstellen, wie du schon gemerkt hast). Und ja, das Feld 'sorting' wird nur beim Manuellen Sortieren befüllt, da die Sortierung sonst (Alphabetisch) ja nicht in einem extra Feld festgehalten werden muss.
Wegen dem manuellen Sortieren etc. bitte ein neues Ticket, wenn es noch keins gibt.

**Comment by Znrl** [comment]
Indirekt hat es damit zu tun, dass man eben bspw. dazu neigt, wenn nach der Sortierungsspalte gefragt wird "sorting" zu nehmen.
Das wäre eben dann kein Problem, wenn das Feld (es existiert ja eh) immer befüllt würde (nicht nur mit nullen). Der rest ist tatsächlich eher offtopic und mehr ne Begründung warum das Sinn machen könnte.

Hab das aber mal gemacht, nichts gefunden das sich danach anhört.
https://github.com/MetaModels/core/issues/804

**Comment by xantippe** [comment]
@haendersonfox bitte testen, ob noch aktuell

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@haendersonfox could you please have a final look at this and tell if your issue has been resolved?

**Comment by ThomasJanotta** [comment]
Hallo, kann bestätigen, dass bei "Sortierung der Mehrfachauswahl" -> id immer noch der Fehler kommt (z.B.: Found 6, expected '10'). Bei Sortierung nach z.B. "Kategorie (type text)" nicht. Dann akzeptiert er mehrere Werte. (aber man sortiert ja he nach Namen (-Feld) ...)
MM 2.0.0 bundle_all, per Composer, keine Zusatzpakete.

**Comment by zonky2** [comment]
getestet mit aktuellem core (a15), dcg (b39), tags (2.0.0) - keine Fehlermeldung

![shot357](https://user-images.githubusercontent.com/1045318/29020570-cf4b76b6-7b62-11e7-8a5b-8bc1c268ace6.jpg)

![shot356](https://user-images.githubusercontent.com/1045318/29020578-d80fd058-7b62-11e7-8b86-b94938c6119e.jpg)

**Comment by richardhj** [comment]
@ThomasJanotta aktuelle Erweiterungen? Sonst kann die Konfiguration zu diesem Fehler führen und dieser sollte dann auch nicht auftauchen

**Comment by ThomasJanotta** [comment]
@zonky2: MM aktuell (a2, b15), sorry, war wohl irgendein cacheproblem im browser, kannst es 'schließen'.

Danke
