### ISSUE TITLE
Useless code

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_tags#40]
I think these lines of code are useless: https://github.com/MetaModels/attribute_tags/blob/afb66f18cddd1fb5957522f2cb20426ab165cbe4/src/MetaModels/Attribute/Tags/MetaModelTags.php#L453-L467

Because we set the $value in this line: https://github.com/MetaModels/attribute_tags/blob/afb66f18cddd1fb5957522f2cb20426ab165cbe4/src/MetaModels/Attribute/Tags/MetaModelTags.php#L468

So we are rendering the values twice.

**Comment by discordier** [comment]
You are right, I forgot to delete that block in 1349e20222ca8e0e06a9d2ab2362508b91c4223d

**Comment by discordier** [comment]
Fixed in dbe75f620c2d82ce6ef711eae28b4ee104d672f7.
Thanks for notifying, recursion prevention should now be working flawless.
