### ISSUE TITLE
Warning: Illegal string offset 'value' in.. 

### ISSUE THREAD

**Issue by wwwebgainss** [MetaModels/attribute_tags#44]
Habe bei der Eingabemaske ein Feld mit Mehrfach-Auswahlmöglichkeiten definiert. Die Optionen werden in der DB auch per MM eingegeben. Nun möchte ich die Miniaturansicht vom Bild ausgeben und bei der Ausgabe bekomme ich folgende Fehlermeldung:

Warning: Illegal string offset 'value' in templates/metamodel_prerendered_p_d.html5 on line 68

#0 templates/metamodel_prerendered_p_d.html5(68): __error(2, 'Illegal string ...', '/web/web9296/we...', 68, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/Render/Template.php(300): include('/web/web9296/we...')
#2 composer/vendor/metamodels/core/src/MetaModels/ItemList.php(815): MetaModels\Render\Template->parse('html5')
#3 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(115): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Content\ModelList))
#4 system/modules/core/classes/Hybrid.php(231): MetaModels\FrontendIntegration\HybridList->compile()
#5 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/MetaModelHybrid.php(102): Contao\Hybrid->generate()
#6 composer/vendor/metamodels/core/src/MetaModels/FrontendIntegration/HybridList.php(54): MetaModels\FrontendIntegration\MetaModelHybrid->generate()
#7 system/modules/core/library/Contao/Controller.php(476): MetaModels\FrontendIntegration\HybridList->generate()
#8 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#9 system/modules/core/modules/Module.php(282): Contao\ModuleArticle->compile()
#10 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#11 system/modules/core/library/Contao/Controller.php(409): Contao\ModuleArticle->generate(false)
#12 system/modules/core/library/Contao/Controller.php(269): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#13 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#14 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#15 index.php(20): Contao\FrontendIndex->run()
#16 {main}

Hat jmd eine Idee wie ich diesen Fehler beheben kann?

**Comment by tim-bec** [comment]
Hallo @wwwebgainss 

das sieht nach einem Problem in deinem (angepassten?) Template aus.
Solche Fragen / Probleme bitte ins Forum https://community.contao.org/de/forumdisplay.php?149-MetaModels oder im irc:  #contao.mm
