### ISSUE TITLE
Sorting bei der Ausgabe reagiert nicht auf die Einstellung von dem Attribut

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_tags#47]
Ich habe in der Auswahl eine Verknüpfung zu einem extra MM mit Wochentagen. Als Sortierung der Mehrfachauswahl ist sorting eingestellt. Im Frontend wird allerdings die Ausgabe in einer mir nicht erschließbaren Reihenfolge gemacht. Eventuell wird da die Reihenfolge ausgegeben, in der die Items ausgewählt wurden?
Auch wenn ich die Sortierung umstelle, reagiert die Ausgabe darauf nicht und die Reihenfolge ändert sich nicht.

Viele Grüße

**Comment by discordier** [comment]
Please try 2.0.0-alpha5 (a0ad4ef98d762297f0930ddbb9791a1f0f4977d8)

**Comment by xantippe** [comment]
@discordier vorab nochmal danke für das nächtliche Fixing...

Mit der alpha5 wird nun eine einheitliche Sortierung ausgegeben @MacKP bei den Items mit der tag-Relation müssen diese für die Speicherung mit einer **Änderung** erneut gespeichert werden...

@discordier zur aktuellen Implementierung hätte ich dennoch einen Änderungsvorschlag: z.Z. werden die Werte in tl_metamodel_tag_relation.value_sorting anhand der gerade eingestellten Sortierung gespeichert (statt der "0" wie vorher)... soweit o.k. - wird die Sortierung der Tags im Attribut umgestellt, hat das dann keinen Einfluss auf die Sortierung der Tags in der Ausgabe (in der Eingabemaske ändert sich jedoch die Reihenfolge).

**Vorschlag:** man belässt die Spalte tl_metamodel_tag_relation.value_sorting der manuellen Sortierung (wenn die "grünen Hamburger" kommen) und in "Sortierung der Mehrfachauswahl" auf "sorting" steht und sortiert die Tags "dynamisch" anhand der eingestellten Sortierung...

**Comment by discordier** [comment]
Kann man machen, mir ging es erstmal darum dass sich MetaModels Tags gleich verhalten wie die "alten" Tags. Also den Bug der Unvorhersehbarkeit zu entfernen.

**Comment by xantippe** [comment]
ja - sehe ich auch so... wollte das als "FR" ablegen, damit ich/wir es nicht vergessen...

**Comment by MacKP** [comment]
The fix is working for me. Sadly I need to change and save the item twice (but ok, better than the bug *g*).

regards (and thx!)
