### ISSUE TITLE
Sortierung automatisch nach Einstellung im BE oder nach value_sorting bei manueller Sortierung

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tags#48]
siehe #47
man belässt die Spalte tl_metamodel_tag_relation.value_sorting der manuellen Sortierung (wenn die "grünen Hamburger" kommen) und in "Sortierung der Mehrfachauswahl" auf "sorting" steht und sortiert die Tags "dynamisch" anhand der eingestellten Sortierung...

**Comment by xantippe** [comment]
Hinweis als "Merker": wenn das Ausgangsfeld für die Sortierung den gleichen Wert enthält, bekommt man in der Eingabemaske bei mehr als einer Zuordnung eine Fehlermeldung i.E. ```Property xyz (tags) did not accept the value (The values differ. Array value mismatch for key 1. Found 'uvw' expected 'vwu').```

z.B. wenn Ausgangsfeld "sorting" ist und keine manuelle Sortierung erfolgte

**Comment by discordier** [comment]
Was bitte ist ein Ausgangsfeld?

**Comment by xantippe** [comment]
geändert => "Sortierung der Mehrfachauswahl"

**Comment by zonky2** [comment]
fixed with https://github.com/MetaModels/attribute_tags/pull/60
