### ISSUE TITLE
Unparsable encoded id value

### ISSUE THREAD

**Issue by seaneble** [MetaModels/attribute_tags#49]
Beim Öffnen der Lightbox eines Tag-Attributes in einem Model erscheint bei uns folgende Meldung:

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(802): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(871): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive(0, 0, NULL)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(609): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection(0)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
#6 composer/vendor/contao-community-alliance/dc-general/contao/backend/generaltree.php(40): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#7 {main}
```

Das Attribut hat folgende Konfiguration: [datenbankdump.txt](https://github.com/MetaModels/attribute_tags/files/263405/datenbankdump.txt)

**Comment by seaneble** [comment]
Offenbar tritt dies nur auf, wenn man auf dasselbe Model referenziert. Andere Models sowie sonstige Datenbanktabellen von Contao sind nicht betroffen.

**Comment by zonky2** [comment]
tags a5, DCG b39
ich habe ein Attribut Mehrfachauswahl angelegt und auf das selbe MM referenziert - bei der Auswahl gab es keine Fehlermeldungen (alle vier Widgets getestet)

![shot314](https://cloud.githubusercontent.com/assets/1045318/22062361/9b082fa2-dd79-11e6-801b-553a45189167.jpg)

![shot315](https://cloud.githubusercontent.com/assets/1045318/22062364/9e3ab2f8-dd79-11e6-97a6-ad3b8d01a60e.jpg)

![shot316](https://cloud.githubusercontent.com/assets/1045318/22062373/a307f84a-dd79-11e6-8093-c20e9e61993d.jpg)

**Comment by seaneble** [comment]
Das Problem tritt nach wie vor auf. Die Fehlermeldung ist nicht verschwunden.

**Comment by zonky2** [comment]
Wie kann ich den Case nachbauen bzw. was habe ich anders gemacht?
![shot317](https://cloud.githubusercontent.com/assets/1045318/22062992/cbb6e280-dd7c-11e6-913c-d4272fb4a6e6.jpg)

**Comment by seaneble** [comment]
![metamodels](https://cloud.githubusercontent.com/assets/1255670/22063799/0db4d6e8-dd81-11e6-918b-2bd40ed9bd5f.png)

Sieht nicht so unterschiedlich aus.

**Comment by seaneble** [comment]
Eine Auswahl bei "Alias" verändert auch nichts.

**Comment by zonky2** [comment]
wie aktuell ist "der Rest"? hast Du die "Hotfix-Pakete" geladen?

**Comment by seaneble** [comment]
Nein, bin noch auf den "stabilen" Versionen.

**Comment by zonky2** [comment]
es gab m.E. eine Anpassung bei den Tags, dass nicht mehr der Alias sondern die Id verwendet wird... kannst Du testweise die neuen/kommenden Branches ausprobieren?

**Comment by zonky2** [comment]
@seaneble kannst Du das checken? - dann könnte das Ticket (wieder) zu...

**Comment by seaneble** [comment]
Das ist alles nicht so einfach, weil ich die Bundle-Pakete installiert habe. Außerdem ist mir aufgefallen, dass ich attribute_tags A6 habe, du nur A5. Die Auflösung des Bundles dauert noch ein bisschen, das ist ganz schön viel Arbeit.

**Comment by richardhj** [comment]
du musst die Bundles nicht auflösen, du kannst deine composer.json einfach ergänzen: http://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen-via-composer (`… as 2.0.0`)

**Comment by seaneble** [comment]
Danke. Die Fehlermeldung besteht weiterhin.

**Comment by zonky2** [comment]
hmm... Frage wäre, was ist bei Dir anders ist

**Comment by seaneble** [comment]
Laut Fehlermeldung ist es ja ein NULL-Wert, der eigentlich ein serialisiertes Array sein sollte. Aber aus welcher Tabelle und aus welchem Datensatz das kommt und wer es an diese Stelle gespeichert hat, entzieht sich meiner Kenntnis.

**Comment by seaneble** [comment]
Eine kleine Analyse mit var_dump bringt mich auch nicht viel weiter als in die Tiefen von dc-general. Offenbar wird irgendwo ein Wert erwartet, der dort nicht ist. Die Objekte sind aber gigantisch groß und von der Struktur verstehe ich nicht viel.

**Comment by zonky2** [comment]
das Ganze ohne "Kundendaten" wirst wahrscheinlich nicht an mich übergeben können - oder? dann könnte ich das lokal mal bei mir einspielen

**Comment by zonky2** [comment]
hier nochmal meine Pakete

![shot318](https://cloud.githubusercontent.com/assets/1045318/22103303/ef462d82-de3a-11e6-8532-a353482f2b76.jpg)

btw: hattest Du nach dem Update das Attribut nochmal aktualisiert?

**Comment by seaneble** [comment]
Ich könnte schon einen Struktur-Export machen. Nur hat der Kunde ja quasi auch für diese Struktur gezahlt, ist also rechtlich schwierig. Wenn es wirklich von Interesse ist, könnten wir auch per TeamViewer herumsuchen.

Versionen stimmen exakt mit meinen überein.

Ja, hatte das Attribut erneut gespeichert.

**Comment by zonky2** [comment]
o.k. - dann Teamviewer... ich melde mich nochmal per E-Mail...

**Comment by zonky2** [comment]
Im Forum hast hast Du anscheinend einen anderen Nickname - hier mal meine E-Mail-Adresse: info@e-spin.de - schick mir doch bitte mal Deine Infos...

**Comment by richardhj** [comment]
Um das zu reproduzieren: Die MM-Eingabemaske ist rendertype ctable und rendermode parented.
Dann sieht man, dass der DCG in https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-39/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php#L162-L165 nach einer pid, fischt, die nicht in der URL gesetzt ist, weil ja die Lightbox geöffnet ist.

**Comment by zonky2** [comment]
@richardhj hmmm.. was hast Du wo, wie eingestellt?

**Comment by richardhj** [comment]
Eingabemaske des MM, auf das referenziert wird ![bildschirmfoto 2017-01-19 um 13 12 51](https://cloud.githubusercontent.com/assets/1284725/22106474/2f411358-de49-11e6-8867-1479b5cf072d.png)
und diesen Mode für das Tags-Attribute
![bildschirmfoto 2017-01-19 um 13 13 51](https://cloud.githubusercontent.com/assets/1284725/22106489/3aa8928e-de49-11e6-8fa1-7218dfe75c8e.png)

Es ist egal, ob das Attribute auf da gleiche MM referenziert.

**Comment by richardhj** [comment]
Das scheint aber ein DCG Fehler zu sein. 
```php
$pid        = $environment->getInputProvider()->getParameter('pid');
$pidDetails = ModelId::fromSerialized($pid);
```
funktioniert scheinbar nicht im Popup

**Comment by zonky2** [comment]
o.k. - kannst Du ein Ticket im DCG aufmachen?

**Comment by richardhj** [comment]
Gemacht.

**Comment by zonky2** [comment]
Supa!

**Comment by richardhj** [comment]
Kann es sein, dass die Konfiguration, wie @seaneble sie verwendet, gar nicht möglich ist?
@seaneble wenn dein MetaModel vom Typ "Elternelement vorhanden" ist, welche List view soll sich denn da aufbauen?

**Comment by richardhj** [comment]
@seaneble Mach doch mal folgendes, geh zu den Code, den ich weiter oben verlinkt habe und ändere die Zeilen ab in
```php
// Special filter for certain modes.
        if ($parentId) {
            $this->addParentFilter($parentId, $config);
        } elseif ($definition->getBasicDefinition()->getMode() == BasicDefinitionInterface::MODE_PARENTEDLIST) {
            $pid        = $environment->getInputProvider()->getParameter('pid');
            if ($pid) {
                $pidDetails = ModelId::fromSerialized($pid);

                $this->addParentFilter($pidDetails, $config);
            }
        }
```
Dann ist der Fehler weg, aber die Auflistung der "Tags" ist falsch, da der elementare Filter fehlt. IMO kann deine Konfiguration nicht funktionieren und das Tags-Attribute-Meta;odel darf nicht vom Typ "Elternelement vorhanden" sein 🤔

**Comment by discordier** [comment]
So dachte ich auch, ich komme auf keinen logischen Zweig wenn ich versuche gedanklich nachzuvollziehen was hierbei die richtige PID waere.

So wie es aussieht hat @seaneble eine Konfiguration wie folgt:
```
Projekt 1
  - Kind Projekt 1.1
  - Kind Projekt 1.2
Projekt 2
  - Kind Projekt 2.1
  - Kind Projekt 2.2
Projekt 3
  - Kind Projekt 3.1
  - Kind Projekt 3.2
```
Und will nun bei `Projekt 1` im Tag-Attribut die Liste der Projekte haben um "vorherige" auszuwaehlen.
Welche sollen denn hierbei gelistet werden?

- PID = 1 - nur Projekt 1.1, nur Projekt 1.2 werden gelistet.
- PID = 2 - nur Projekt 2.1, nur Projekt 2.2 werden gelistet.
- PID = 3 - nur Projekt 3.1, nur Projekt 3.2 werden gelistet.

Dadurch dass die Projekte Kindelemente eines anderen Projekts sind, macht es doch keinerlei Sinn diese in einem tag nochmal gesondert zuzuweisen.

Ein Fallback den ich mir vorstellen koennte, wir gehen ohne PID von 0 aus, was aber bei parented implizit schon falsch ist, denn ein Kind ohne parent wird automatisch geloescht werden und nicht existieren koennen (man kann es ja nichtmal anlegen).

**Comment by seaneble** [comment]
Ähm, bei @discordier komme ich nicht mit. Meine Struktur hat keine Kindprojekte. Es gibt nur Projekte auf einer Ebene, die in der Tat mit "Vorprojekten", also Datensätzen aus dem gleichen MetaModel verlinkt sind. Dabei gibt es im Prinzip keinen Filter, höchstens die Selbstreferenz wäre zu verbieten.

**Comment by richardhj** [comment]
Skizziere doch bitte mal, wie dein MetaModel in der List View ausschaut, und welchen Output du in der Lightbox dir vorstellst.
Siehst du das auch so, dass "Elternelement vorhanden" nicht bei dem Metamodel aktiviert sein darf, auf das das Tag-Attribut referenziert?

**Comment by zonky2** [comment]
> höchstens die Selbstreferenz wäre zu verbieten

das wäre m.E. nicht Zielführend - b.B. bei dem Handbuch-Beispiel könnten die Mitarbeiter andere Mitarbeiter als "Urlaubsvertretung" o.ä. auswählen - "Basistabelle" und "Auswahltabelle" wären hier als "mm_mitarbeiter" die selbe...

**Comment by discordier** [comment]
Die Mitarbeiter koennen jedoch NICHT parented sein, zumindest nicht unterhalb von sich selbst und sollten sie parented sein, wie soll man aus dem Kontext eines Mitarbeiters auf die richtige PID kommen?
Soll es dann hierbei die PID des aktuellen Mitarbeiters sein? Also quasi eine Sibling-Auswahl?

**Comment by zonky2** [comment]
=> korrekt "Sibling-Auswahl" - da alle Mitarbeiter im Prinzip auf "einer Stufe" stehen

**Comment by richardhj** [comment]
Also eine allgemeine Lösung gibt es nicht, mancher will Siblings auswählen, mancher will alle auswählen können (ohne parent).
Ist das Problem nicht gelöst, wenn man statt des Pickers ein anderes Attribut nimmt?

**Comment by seaneble** [comment]
Der Picker ist das einzige, was bei ca. 20000 Datensätzen noch hilft.

**Comment by zonky2** [comment]
tja... und nu?

**Comment by discordier** [comment]
@seaneble und was ist in diesem Falle der korrekte parent?

**Comment by zonky2** [comment]
>und was ist in diesem Falle der korrekte parent?

@seaneble könntest Du die Infos noch posten?

**Comment by seaneble** [comment]
@discordier was ist in diesem Fall ein parent? Was meinst du damit?
In meinem Fall handelt es sich um eine Selbstreferenz, das Model im Picker ist also das gleiche wie der Elterndatensatz.

**Comment by richardhj** [comment]
> Skizziere doch bitte mal, wie dein MetaModel in der List View ausschaut, und welchen Output du in der Lightbox dir vorstellst.

**Comment by seaneble** [comment]
Ich habe ehrlich gesagt keine Ahnung, wie ich es mir vorstelle. Wir haben damals das Model zusammengeklickt und einfach mal ausgewählt, dass wir da einen Picker haben wollen. Ich war im Hinterkopf davon ausgegangen, dass das dann so ähnlich wie beim File- oder PagePicker läuft:

  * Lighbox öffnet sich
  * Backend-Listenansicht des Ziel-Models öffnet sich
  * Über Filter, Blättern, Suchen etc. können Datensätze gefunden werden
  * Haken setzen
  * Änderungen anwenden
  * Lightbox schließt sich
  * Ausgewählte Datensätze werden unterhalb des Buttons in Kurzform angezeigt

Ob das aber eine realistische Vorstellung ist, vermag ich nicht zu sagen.

**Comment by zonky2** [comment]
im Prinzip funktioniert das mit dem Popup-Picker genau so - lediglich ein "Filtern, Blättern, Suchen" gibt es in der Form nicht - normalerweise werden die Werte in einer Hierarchie angezeigt, es geht aber auch mit einer hierarchischen Baumdarstellung (wenn das referenzierte MM so aufgebaut ist).

siehe Screenshots

M.E. kommen hier eher die "Fragezeichen" zum Thema "Selbstreferenzierung" auf, wie genau die Sache für Deinen Anwendungsfall aussehen soll(te) bzw. was nicht funktioniert hat(te).

![shot321](https://cloud.githubusercontent.com/assets/1045318/22976881/d7242116-f38c-11e6-85dc-8f7e50c48ac0.jpg)
~~~~~~~~~~~~~
![shot322](https://cloud.githubusercontent.com/assets/1045318/22976888/dc7dad44-f38c-11e6-9b18-c6d1a2dc370d.jpg)

**Comment by zonky2** [comment]
... vielleicht setzen wir den Meilenstein auf "Future" bis mal wieder ein passender Use case auftaucht - eine "Selbstreferenzierung" ist zumindest möglich...

![shot323](https://cloud.githubusercontent.com/assets/1045318/22977196/f3657dc4-f38d-11e6-9379-0307b2eafdca.jpg)

**Comment by richardhj** [comment]
Also wir waren ja eigentlich schon weiter und drehen uns nur im Kreis.
Wir hatten gesagt, dass eigentlich sowohl die Sibling-Auswahl, als auch die Root-Auswahl unter Umständen geeignete Use-Cases sein können (Welcher Fall das bei @seaneble, wissen wir immer noch nicht).
Und je nachdem muss die passende `pid` herausgefunden werden und der URL (Klick auf Picker Button) angehängt werden (das sollte ausreichen?).
Zusammenfassend: wenn rendertype==ctable && rendermode==parented && attribute==file picker --> dann muss der Redakteur die Auswahl treffen für mode∈['sibling','root'] --> entsprechende `pid` dem Picker anhängen

**Comment by zonky2** [comment]
@richardhj - o.k. Frage für mich ist, ist das "Bug oder (künftiges) Feature" und soll das Thema noch in 2.0.0 oder in 2.? bearbeitet werden...

... ich bin für letzteres, da offensichtlich niemand einen entsprechenden "Leidens druck" verspürt

**Comment by seaneble** [comment]
Nein, Druck ist nicht da. Ich kann auch gerne weitere Infos liefern, oder euch das Teil per TeamViewer zeigen. Ich verstehe aber auch eure Rückfragen nicht.

    Welcher Fall das bei @seaneble, wissen wir immer noch nicht

Solche Sachen hatte ich ja durchaus oben schon erläutert, daher sehe ich da auch eher einen Kreis-Bezug.

**Comment by richardhj** [comment]
Streng genommen ist es ein Bug…
@seaneble Ist ja auch kein Problem, da ich denke, dass man dein Problem auf jeden Fall lösen kann :) Aber da du meine oder auch xtras Rückfragen nicht verstanden hast, bin ich mir nicht ganz sicher, ob ich das Problem umfassend verstanden hatte. Hattest du eigentlich mal https://github.com/MetaModels/attribute_tags/issues/49#issuecomment-273779294 (nur ne if-condition einbauen) ausprobiert? :)

**Comment by seaneble** [comment]
Wenn ich das einbaue (das zusätzliche `if`) erhalte ich auf jeden Fall Daten:

![lightbox](https://cloud.githubusercontent.com/assets/1255670/23057887/7dfff6a2-f4f2-11e6-9751-2ad0a5207399.png)

Im Sinne dieses Tickets wäre der Fehler damit behoben. Filterung etc. wäre natürlich eine feine Sache, ist aber ein anderes Thema.

**Comment by richardhj** [comment]
Aber doch bitte das Ticket nicht schließen 😄

**Comment by seaneble** [comment]
Naja, wenn es eine Code-Änderung in DC_General benötigt, hat es hier ja eigentlich nichts zu suchen, oder?

**Comment by richardhj** [comment]
Der fehlende `pid` Parameter muss aber irgendwie von dem tags attribute kommen. Mit deiner Änderung wurde der ja nur ausgeknockt

**Comment by zonky2** [comment]
denke ich auch - daher "wrong rep"... Frage ist, wo man die Einstellung hin packt - in das Popup (dann DCG) oder als Option wie die "Anzeige Baumstruktur-Ebene" dann zus. in MM

**Comment by zonky2** [comment]
@richardhj willst Du zu dem Thema noch einen PR machen? ansonsten schiebe ich das zu 2.1

**Comment by richardhj** [comment]
In naher Zukunft werd ich keinen PR machen (können) :)

**Comment by zonky2** [comment]
o.k. - dann 2.1 ...

**Comment by plorenz-etes** [comment]
@zonky2 Hier wie besprochen der aktuelle Strack-Trace:

![image](https://user-images.githubusercontent.com/43336309/112836133-78bdcc80-909a-11eb-9440-45c3311f2bb2.png)
![image](https://user-images.githubusercontent.com/43336309/112836187-8a9f6f80-909a-11eb-83e8-01f23332e007.png)

```
ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException:
Unparsable encoded id value: ''

  at vendor/contao-community-alliance/dc-general/src/Data/ModelId.php:117
  at ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized()
     (vendor/contao-community-alliance/dc-general/src/BaseConfigRegistry.php:156)
  at ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig()
     (vendor/contao-community-alliance/dc-general/src/BaseConfigRegistry.php:178)
  at ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
     (vendor/contao-community-alliance/dc-general/src/Contao/View/Contao2BackendView/TreePicker.php:1022)
  at ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->getTreeCollectionRecursive()
     (vendor/contao-community-alliance/dc-general/src/Contao/View/Contao2BackendView/TreePicker.php:1132)
  at ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->loadCollection()
     (vendor/contao-community-alliance/dc-general/src/Contao/View/Contao2BackendView/TreePicker.php:819)
  at ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->generatePopup()
     (vendor/contao-community-alliance/dc-general/src/Controller/BackendTreeController.php:144)
  at ContaoCommunityAlliance\DcGeneral\Controller\BackendTreeController->runBackendTree()
     (vendor/contao-community-alliance/dc-general/src/Controller/BackendTreeController.php:73)
  at ContaoCommunityAlliance\DcGeneral\Controller\BackendTreeController->generalTreeAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:31)
  at require('/var/www/vhosts/heidehof/htdocs/website/web/index.php')
     (web/app.php:4)
```

**Comment by zonky2** [comment]
Das problem gibt es nur dann, wenn die Tabelle eine Kindtabelle einer anderen Tabelle ist - ob die Parent-Tabelle von MM oder Contao ist, ist egal

**Comment by zonky2** [comment]
@plorenz-etes: Wir haben uns die Sache beim MM-call 30.03.2021 zusammen angesehen.

Die Einstellung "Popup-Widget" verwendet den "treepicker" aus dem DCG und der kommt an der Stelle mit dem "Parented" nicht klar - es müsste hier noch die Einstellung geben, ob das Model "parented" oder "flat" ist.

Aktuell könnte man das wohl nur über einen eigenen Eventlistener lösen, der für den Picker von "parented" auf "flat" umstellt, oder die Relation von Kindtabelle zu einen Attribut Einzelauswahl [select] umbauen.

**Comment by zonky2** [comment]
gefixt in MM 2.2 mit neuer Einstellung von DCG
