### ISSUE TITLE
Taxonomy changes and updating MetaModels Tags-field

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/attribute_tags#53]
Hi,

I have a question. If I use the attribute in my installation and the related table for the Tags field get new items or items get removed, I get an error in the backend view of the editor mask.
Is there a solution or work-around for this or maybe the issue is already solved?
The error shows up by saving/updating the data. It says that the ids in the database differ to the ids from the widget.

Environment: contao 3.5.17

- contao-community-alliance/dc-general	dev-develop @ 7841fa	2016-06-07 20:14:53	LGPL-3.0+
- metamodels/core	dev-master @ d6ca59	2016-06-15 02:14:42	LGPL-3.0+
- metamodels/attribute_tags	dev-develop @ dd488e	2016-03-15 21:44:09	LGPL-3.0+

THX

**Comment by zonky2** [comment]
>  I get an error in the backend view of the editor mask

which error? pls post the stack trace...

**Comment by richardhj** [comment]
And as a precaution… please use the up-to-date hotfix-branches (dev-hotfix instead of dev-master). See http://metamodels.readthedocs.io/de/latest/manual/install.html#test-von-speziellen-paketen-via-composer

**Comment by zonky2** [comment]
@MoniqueHahnefeld 
> which error? pls post the stack trace...

**Comment by zonky2** [comment]
@MoniqueHahnefeld pls add more informations

**Comment by zonky2** [comment]
no feedback
