### ISSUE TITLE
"deepDelete" at referenced Items

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tags#59]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_tags/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |                                  |
| Contao version:                     |          |                                  |
| MetaModels version core:            |    b15      |                                  |
| MetaModels version attribute:       |          |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |          |                                  |
| DCG version:                        |    a39      |                                  |

## Issue description

after delete a tag item we have error e.g. at https://github.com/MetaModels/attribute_tags/blob/b2c33d09c0582f6ab6fd0e77e3b1e2576b7c444a/src/MetaModels/Attribute/Tags/AbstractTags.php#L386 because the array node is empty

temporary bugfix:
```diff
-                if (!array_key_exists('tag_value_sorting', $tags[$valueId])) {
+                if (!array_key_exists('tag_value_sorting', (array) $tags[$valueId])) {
```

## Steps to reproduce

* two MMs with relation per tags
* insert any values...
* delete a item from the tags MM
* save a item which have the tag as selected option

Question: we should delete all tags items if we delete the item at MM?

**Comment by discordier** [comment]
Isn't #64 exactly this?

**Comment by zonky2** [comment]
> Isn't #64 exactly this?

ohhh yeah!
