### ISSUE TITLE
Tags attribute does not handle translated aliases property

### ISSUE THREAD

**Issue by bezin** [MetaModels/attribute_tags#69]
# Issue Description

I have a MM Event with an tags attribute Tickets, that references a MM Ticket. Both are translateble (EN & DE).

The MM Tickets has a translated text `name` and a translated alias generated from that name. 

The ticket tags attribute settings are the following:
Table: mm_ticket
Name: mm_ticket.name
Alias: mm_ticket.alias
Sorting: Name
Sort Dir: Ascending
Filter: none

# Steps to reproduce
1. Create the setting explained above.
2. Create new Event (DE) and select some tickets. Save.
The ticket values are stored
3. Switch to EN
The ticket values are missing. However, this only happens with tickets that actually have a different name (and hence alias) in DE and EN. Others are displayed correctly.

Since the tags attribute itself is not translated, I expect the values to be the same in DE and EN. 

# Versions
PHP 7.2.6
Contao 4.4.20
MetaModels 2.1

**Comment by bezin** [comment]
It is not limited to the checkbox menu, but also happens with the picker

**Comment by zonky2** [comment]
Same at MM 2.0

**Comment by zonky2** [comment]
Workaround: switch alias to id

**Comment by discordier** [comment]
API extension is underway in MM/core in the translated MetaModel feature branch.

**Comment by zonky2** [comment]
For the same problem we wrote an own eventlistener, for translated text and untranslated alias. The listener always generates the alias using the fallback language and saves it.

**Comment by zonky2** [comment]
> API extension is underway in MM/core in the translated MetaModel feature branch.

@zonky2 check this

**Comment by zonky2** [comment]
Checked - works fine
