### ISSUE TITLE
Catch warning

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tags#79]
Catch warning "array_key_exists()" in BE at edit item - but not every item... hmmm?

https://github.com/MetaModels/attribute_tags/blob/d09c2cd18b299a48532caa0de8c70b7944282a8e/src/Attribute/MetaModelTags.php#L274

![screenshot_516](https://user-images.githubusercontent.com/1045318/55785330-872c0b80-5ab2-11e9-91db-ac31d3faefa9.jpg)

**Comment by baumannsven** [comment]
@zonky2 More details please

**Comment by zonky2** [comment]
done

**Comment by discordier** [comment]
Strange values in the stack trace... `['r', 'S']` is not a valid value list, it should be an array of array having the ids as key.

**Comment by zonky2** [comment]
the error never occurred again - hmm
